- name: Install base packages
  hosts: all, localhost
  tasks:
    - name: Update repositories cache and install packages
      apt:
        name:
          - git
          - zsh
          - tmux
          - open-vm-tools
          - curl
          - openvpn
          - mosh
          - golang
          - pipenv
          - python3-pip
          - ttyrec
          - neofetch
          - htop
          - python
          - python3
          - build-essential
          - fswatch
          - xsltproc
          - smbclient
          - cifs-utils
          - nfs-common
          - mc
          - ranger
          - openssh-server
          - nmap
          - masscan
          - ldap-utils
          - net-tools
          - jq
          - nikto
          - binwalk
          - dos2unix
          - john
          - libcurl4-openssl-dev
          - make
          - zlib1g-dev
          - gawk
          - g++
          - gcc
          - libreadline6-dev
          - libssl-dev
          - libyaml-dev
          - libsqlite3-dev
          - sqlite3
          - autoconf
          - libgdbm-dev
          - libncurses5-dev
          - automake
          - libtool
          - bison
          - pkg-config
          - proxychains
          - sshuttle
          - tcpdump
          - whois
          - aptitude
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - virtualenv
          - python3-setuptools
          - pssh
          - imagemagick
          - expect
          - fdupes
          - unzip
          - p7zip-full
          - sqlmap
          - nload
          - minicom
          - socat
          - gnupg
          - libpq-dev
          - libpcap0.8-dev
        update_cache: yes

    - name: Set up authorized_keys for the root user
      authorized_key: user=root key="{{ item }}"
      with_file:
        - files/keys/id_rsa.pub

    - name: Get GPG keys for RVM install package
      shell: gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

    - name: Install RVM
      shell: curl -sSL https://get.rvm.io | bash -s stable
      args:
        warn: false

    - name: Clone Repository
      git:
        repo: https://github.com/rapid7/metasploit-framework
        dest: "/opt/metasploit"

    - name: Install Ruby
      shell: |
        source /etc/profile.d/rvm.sh
        rvm install ruby-`(cat .ruby-version)`
        gem install bundler
        bundle install
      args:
        chdir: "/opt/metasploit"
        executable: /usr/bin/zsh

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
    
    - name: Install Updog
      pip:
        name: updog
    
    - name: Clone oh-my-zsh repo
      git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/root/.oh-my-zsh
    
    - name: Clone zsh-autosuggestions
      git: repo=https://github.com/zsh-users/zsh-autosuggestions dest=/root/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Clone Powerlevel10k
      git: repo=https://github.com/romkatv/powerlevel10k.git dest=/root/.oh-my-zsh/custom/themes/powerlevel10k depth=1
    
    - name: remove standard zshrc
      file: path=/root/.zshrc state=absent

    - name: deploy .zshrc
      copy: src=confs/zshrc dest=/root/.zshrc owner=root

    - name: Copy Custom P10K Config
      copy: src=confs/p10k.zsh dest=/root/.p10k.zsh owner=root

    - name: Set zsh as default shell
      user: name=root shell=/bin/zsh

    - name: Clone OhMyTmux
      git: repo=https://github.com/gpakosz/.tmux.git dest=/root/.tmux

    - name: Setup OhMyTmux
      file: path=/root/.tmux.conf 
          src=/root/.tmux/.tmux.conf  
          state=link 
          force=yes
    
    - name: Copy Custom Tmux Config
      copy: src=confs/tmux.conf.local dest=/root/.tmux.conf.local owner=root
    
    ##### SECLISTS
    - name: Clone SecLists
      git: repo=https://github.com/danielmiessler/SecLists.git dest=/opt/seclists force=yes

    ##### RESPONDER
    - name: Clone Responder
      git: repo=https://github.com/lgandx/Responder dest=/opt/responder

    - name: Clone ExploitDB
      git: repo=https://github.com/offensive-security/exploitdb.git dest=/opt/exploitdb

    - name: Clone TestSSl
      git: repo=https://github.com/drwetter/testssl.sh.git dest=/opt/testssl.sh depth=1

    - name: Get Gobuster & Gowitness
      shell:  |
        go get github.com/OJ/gobuster
        go get -u github.com/sensepost/gowitness
        go get github.com/bennettwarner/ChadTunnel
        go get -u github.com/atredispartners/flamingo

    - name: Get Latest Chromium
      git: repo=https://github.com/scheib/chromium-latest-linux.git dest=/opt/chromium
    
    - name: Install Chromium
      shell: bash /opt/chromium/update.sh

    - name: Clone Nmap Bootstrap
      git: repo=https://github.com/honze-net/nmap-bootstrap-xsl.git dest=/opt/nmap-bootstrap    
      
    - name: Get Amass Binary
      shell: curl -s https://api.github.com/repos/OWASP/Amass/releases/latest | grep "browser_download_url.*amass_linux_amd64.zip" | cut -d '"' -f 4
      register: "download_url"
      args:
        warn: no

    - name: Download latest Amass release
      get_url:
        url: "{{ download_url.stdout }}"
        dest: /opt/amass_linux_amd64.zip
        tmp_dest: /tmp/
        force: yes
        headers:
          Accept: "application/octet-stream"

    - name: Extract Amass
      unarchive:
        src: /opt/amass_linux_amd64.zip
        dest: /opt/
  
    - name: Delete Zip
      file:
        path: /opt/amass_linux_amd64.zip
        state: absent

    - name: Download terraform release
      get_url:
        url: https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
        dest: /opt/terraform.zip
        tmp_dest: /tmp/
        force: yes
        headers:
          Accept: "application/octet-stream"

    - name: Extract terraform
      unarchive:
        src: /opt/terraform.zip
        dest: /opt/
  
    - name: Delete Zip
      file:
        path: /opt/terraform.zip
        state: absent

    - name: Get CrackMapExec Binary
      shell: curl -s https://api.github.com/repos/byt3bl33d3r/CrackMapExec/releases/latest | grep "browser_download_url.*cme-ubuntu-latest.zip" | cut -d '"' -f 4
      register: "download_url"
      args:
        warn: no

    - name: Download CrackMapExec release
      get_url:
        url: "{{ download_url.stdout }}"
        dest: /opt/cme.zip
        tmp_dest: /tmp/
        force: yes
        headers:
          Accept: "application/octet-stream"

    - name: Extract CrackMapExec
      unarchive:
        src: /opt/cme.zip
        dest: /opt/
  
    - name: Delete Zip
      file:
        path: /opt/cme.zip
        state: absent

    - name: Making CME Executable
      file: dest=/opt/cme mode=a+x
    
    - name: Install WPScan
      gem:
        name: wpscan
        state: present

    - name: Install Proxy.py
      pip:
        name: proxy.py

    - name: Install NodeJS & Mono Repos
      shell:  |
        curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
      args:
        warn: no
    
    - name: Install Nodejs & Mono
      apt:
        name: 
          - nodejs
          - mono-complete
          - msbuild
          - mono-roslyn
        update_cache: yes
    
    - name: Install "TLDR" node.js package globally.
      npm:
        name: tldr
        global: yes
    
    - name: 
      git: repo=https://github.com/diego-treitos/linux-smart-enumeration.git dest=/opt/linux-smart-enumeration

    - name: Get Ruler Binary
      shell: curl -s https://api.github.com/repos/sensepost/ruler/releases/latest | grep "browser_download_url.*ruler-linux64" | cut -d '"' -f 4
      register: "download_url"
      args:
        warn: no

    - name: Download latest Ruler release
      get_url:
        url: "{{ download_url.stdout }}"
        dest: /opt/ruler-linux64
        tmp_dest: /tmp/
        force: yes
        headers:
          Accept: "application/octet-stream"
    
    - name: Clone Spraying Toolkit Repo
      git:
        repo: https://github.com/byt3bl33d3r/SprayingToolkit
        dest: "/opt/sprayingtoolkit"

    - name: Install via pipenv
      shell: pipenv install
      args:
        chdir: "/opt/sprayingtoolkit"


    # - name: 
    #   git: repo= dest=/opt/

    # - name: 
    #   git: repo= dest=/opt/
