- name: Install base packages
  hosts: all, localhost
  tasks:
    - name: Update repositories cache and install packages
      apt:
        name:
          - git
          - zsh
          - tmux
          - zip
          - tree
          - open-vm-tools
          - curl
          - openvpn
          - mosh
          - golang
          - pipenv
          - python3-pip
          - neofetch
          - htop
          - python
          - python3
          - build-essential
          - fswatch
          - xsltproc
          - smbclient
          - cifs-utils
          - nfs-common
          - ranger
          - openssh-server
          - nmap
          - masscan
          - ldap-utils
          - net-tools
          - jq
          - nikto
          - dos2unix
          - libcurl4-openssl-dev
          - make
          - zlib1g-dev
          - gawk
          - g++
          - gcc
          - libreadline6-dev
          - libssl-dev
          - libyaml-dev
          - libsqlite3-dev
          - sqlite3
          - autoconf
          - libgdbm-dev
          - libncurses5-dev
          - automake
          - libtool
          - bison
          - pkg-config
          - proxychains-ng
          - sshuttle
          - tcpdump
          - whois
          - aptitude
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - virtualenv
          - python3-setuptools
          - imagemagick
          - expect
          - unzip
          - p7zip-full
          - socat
          - gnupg
          - libpq-dev
          - libxml2-dev
          - libxslt1-dev
          - exiftool
          - python-dev
          - python3-testresources
          - fping
          - grc
          - autossh
          - docker.io
          - docker-compose
          - wireguard
          - libpcap-dev
          - ruby2.7-dev
        update_cache: yes

    - name: Set up authorized_keys for the root user
      authorized_key: user=root key="{{ item }}"
      with_file:
        - files/keys/b-id_rsa.pub

    - name: Set up authorized_keys for the root user
      authorized_key: user=root key="{{ item }}"
      with_file:
        - files/keys/z-id_rsa.pub

    - name: Install cargo packages
      shell: |
        source $HOME/.cargo/env
        cargo install feroxbuster
      args:
        executable: /bin/bash
        warn: no

    - name: Get GPG keys for RVM install package
      shell: gpg --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

    - name: Install RVM
      shell: curl -sSL https://get.rvm.io | bash -s stable
      args:
        warn: false

    - name: Clone Repository
      git:
        repo: https://github.com/rapid7/metasploit-framework
        dest: "/opt/metasploit"

    - name: Install Ruby
      shell: |
        source /etc/profile.d/rvm.sh
        rvm install ruby-`(cat .ruby-version)`
        gem install bundler
        bundle install
      args:
        chdir: "/opt/metasploit"
        executable: /usr/bin/zsh

    - name: Clone Repository
      git:
        repo: https://github.com/urbanadventurer/WhatWeb.git
        dest: "/opt/whatweb"

    - name: Install Whatweb
      shell: |
        source /etc/profile.d/rvm.sh
        bundle install
      args:
        chdir: "/opt/whatweb"
        executable: /usr/bin/zsh

    - name: Install Updog
      pip:
        name: updog

    - name: Install lsassy
      pip:
        name: lsassy

    ##### SECLISTS
    - name: Clone SecLists
      git: repo=https://github.com/danielmiessler/SecLists.git dest=/opt/seclists force=yes

    ##### RESPONDER
    - name: Clone Responder
      git: repo=https://github.com/lgandx/Responder dest=/opt/responder

    - name: Clone onesixtyone
      git: repo=https://github.com/trailofbits/onesixtyone dest=/opt/onesixtyone

    - name: Clone ExploitDB
      git: repo=https://github.com/offensive-security/exploitdb.git dest=/opt/exploitdb

    - name: Clone TestSSl
      git: repo=https://github.com/drwetter/testssl.sh.git dest=/opt/testssl.sh depth=1

    - name: Get Gobuster
      shell: |
        go get -u gorm.io/gorm
        go get -u github.com/sensepost/gowitness
        go get github.com/OJ/gobuster
        go get github.com/bennettwarner/ChadTunnel
        GO111MODULE=on go get github.com/projectdiscovery/dnsx/cmd/dnsx
        GO111MODULE=on go get github.com/projectdiscovery/httpx/cmd/httpx
        go get github.com/jpillora/chisel
        GO111MODULE=on go get github.com/projectdiscovery/nuclei/v2/cmd/nuclei
        GO111MODULE=on go get github.com/schollz/croc/v9

    - name: Get Latest Chromium
      git: repo=https://github.com/scheib/chromium-latest-linux.git dest=/opt/chromium

    - name: Install Chromium
      shell: bash /opt/chromium/update.sh

    - name: Clone Nmap Bootstrap
      git: repo=https://github.com/honze-net/nmap-bootstrap-xsl.git dest=/opt/nmap-bootstrap

    - name: Disable Auto-updates
      shell: sed -i 's/Upgrade \"1\"/Upgrade \"0\"/' /etc/apt/apt.conf.d/20auto-upgrades
      args:
        warn: no

    - name: create cme dir
      file:
        path: /opt/crackmapexec
        state: directory

    - name: Copy Cloudflared Binary
      copy: src=binaries/cloudflared dest=/usr/bin/cloudflared owner=root

    - name: Making Cloudflared Executable
      file: dest=/usr/bin/cloudflared mode=a+x

    - name: Copy Gowitness Binary
      copy: src=binaries/cloudflared dest=/usr/bin owner=root

    - name: Making Gowitness Executable
      file: dest=/usr/bin/cloudflared mode=a+x

    - name: Copy smug Binary
      copy: src=binaries/gowitness dest=/usr/bin/gowitness owner=root

    - name: Making smug Executable
      file: dest=/usr/bin/gowitness mode=a+x

    - name: Copy windapsearch Binary
      copy: src=binaries/windapsearch dest=/usr/bin/windapsearch owner=root

    - name: Making windapsearch Executable
      file: dest=/usr/bin/windapsearch mode=a+x

    - name: Copy magescan Binary
      copy: src=binaries/magescan.phar dest=/opt/magescan.phar owner=root

    - name: Install Proxy.py
      pip:
        name: proxy.py

    - name: Install Nmap-Parse-Output
      git: repo=https://github.com/ernw/nmap-parse-output.git dest=/opt/nmap-parse-output

    - name: Clone Spraying Toolkit Repo
      git:
        repo: https://github.com/byt3bl33d3r/SprayingToolkit
        dest: "/opt/sprayingtoolkit"

    - name: Install Spraying Toolkit via pipenv
      shell: pipenv install --three
      args:
        chdir: "/opt/sprayingtoolkit"

    - name: Clone GhostCat Repo
      git:
        repo: https://github.com/00theway/Ghostcat-CNVD-2020-10487.git
        dest: "/opt/ghostcat"

    - name: Clone Impacket repo
      git:
        repo: https://github.com/SecureAuthCorp/impacket
        dest: "/opt/impacket"

    - name: Install Impacket via pipenv
      shell: |
        pipenv install --three
        pipenv run python3 setup.py install
      args:
        chdir: "/opt/impacket"

    - name: Clone WafW00f repo
      git:
        repo: https://github.com/EnableSecurity/wafw00f.git
        dest: "/opt/wafw00f"

    - name: Install WafW00f via pipenv
      shell: |
        pipenv install --three
        pipenv run python3 setup.py install
      args:
        chdir: "/opt/wafw00f"

    - name: Clone Enum4linux-ng repo
      git:
        repo: https://github.com/cddmp/enum4linux-ng.git
        dest: "/opt/enum4linux-ng"

    - name: Install enum4linux-ng via pipenv
      shell: |
        pipenv install --three
        pipenv run pip3 install -r requirements.txt
      args:
        chdir: "/opt/enum4linux-ng"

    - name: Clone SQLMap repo
      git:
        repo: https://github.com/sqlmapproject/sqlmap.git
        dest: "/opt/sqlmap"

    - name: Clone Bloodhound.py repo
      git:
        repo: https://github.com/fox-it/BloodHound.py
        dest: "/opt/bloodhound.py"

    - name: Install Bloodhound.py via pipenv
      shell: |
        pipenv install --three
        pipenv run python3 setup.py install
      args:
        chdir: "/opt/bloodhound.py"

    - name: Clone MITM6 repo
      git:
        repo: https://github.com/fox-it/mitm6
        dest: "/opt/mitm6"

    - name: Install MITM6 via pipenv
      shell: |
        pipenv install --three
        pipenv run python3 setup.py install
      args:
        chdir: "/opt/mitm6"

    - name: Clone krbrelayx Repo
      git:
        repo: https://github.com/dirkjanm/krbrelayx.git
        dest: "/opt/krbrelayx"

    - name: Install krbrelayx via pipenv
      shell: |
        pipenv install --three
        pipenv run pip3 install ldap3
        pipenv run pip3 install impacket
      args:
        chdir: "/opt/krbrelayx"

    - name: Clone PrivExchange Repo
      git:
        repo: https://github.com/dirkjanm/PrivExchange.git
        dest: "/opt/privexchange"

    - name: Install PrivExchange via pipenv
      shell: |
        pipenv install --three
        pipenv run pip3 install -r requirements.txt
        pipenv run pip3 install impacket
      args:
        chdir: "/opt/privexchange"

    - name: Clone PayloadAllTheThings
      git: repo=https://github.com/swisskyrepo/PayloadsAllTheThings.git dest=/opt/payloadallthethings

    - name: Clone Enum4Linux
      git: repo=https://github.com/portcullislabs/enum4linux.git dest=/opt/enum4linux

    - name: Install modules via PIP
      pip:
        name:
          - ldap3
          - dnspython
          - ldapdomaindump
          - roadrecon
          - adidnsdump
          - aws-consoler
          - pypykatz

    - name: Clone BloodHound
      git: repo=https://github.com/BloodHoundAD/BloodHound.git dest=/opt/bloodhound

    - name: Clone NTLMRelayX-Prettyloot
      git: repo=https://github.com/mpgn/ntlmrelayx-prettyloot.git dest=/opt/ntlmrelayx-prettyloot

    - name: Clone hash-identifier
      git: repo=https://github.com/blackploit/hash-identifier.git dest=/opt/hash-identifier

    - name: Clone sharpsploit
      git: repo=https://github.com/cobbr/SharpSploit.git dest=/opt/sharpsploit

    - name: Clone powersploit
      git: repo=https://github.com/PowerShellMafia/PowerSploit.git dest=/opt/powersploit

    - name: Clone adconnectdump
      git: repo=https://github.com/fox-it/adconnectdump.git dest=/opt/adconnectdump

    - name: Clone SharpCollection
      git: repo=https://github.com/Flangvik/SharpCollection.git dest=/opt/sharpcollection

    - name: Clone PowerSharpPack
      git: repo=https://github.com/S3cur3Th1sSh1t/PowerSharpPack.git dest=/opt/powersharppack

    - name: Clone DPAT
      git: repo=https://github.com/bennettwarner/DPAT.git dest=/opt/dpat

    - name: Clone IPRanger
      git: repo=https://github.com/bennettwarner/ipranger.git dest=/opt/ipranger

    - name: Clone nmap2md
      git: repo=https://github.com/vdjagilev/nmap2md.git dest=/opt/nmap2md

    - name: Clone Eavesarp Repo
      git:
        repo: https://github.com/bennettwarner/eavesarp.git
        dest: "/opt/eavesarp"

    - name: Get LaZagne Binary
      shell: curl -s https://api.github.com/repos/AlessandroZ/LaZagne/releases/latest | grep "browser_download_url.*.exe" | cut -d '"' -f 4
      register: "download_url"
      args:
        warn: no

    - name: Download latest LaZagne release
      get_url:
        url: "{{ download_url.stdout }}"
        dest: /opt/lazagne.exe
        tmp_dest: /tmp/
        force: yes
        headers:
          Accept: "application/octet-stream"

    - name: Copy Nessus Installer
      copy: src=binaries/Nessus-8.14.0-debian6_amd64.deb dest=/opt/Nessus-8.14.0-debian6_amd64.deb owner=root

    - name: Setup Links
      file: path=/usr/bin/msfconsole
        src=/opt/metasploit/msfconsole
        state=link

    - name: Setup Links
      file: path=/usr/bin/msfupdate
        src=/opt/metasploit/msfupdate
        state=link

    - name: Setup Links
      file: path=/usr/bin/msfdb
        src=/opt/metasploit/msfdb
        state=link

    - name: Setup Links
      file: path=/usr/bin/msfvenom
        src=/opt/metasploit/msfvenom
        state=link

    - name: Setup Links
      file: path=/usr/bin/testssl
        src=/opt/testssl.sh/testssl.sh
        state=link

    - name: Setup Links
      file: path=/usr/bin/responder
        src=/opt/responder/Responder.py
        state=link

    - name: Setup Links
      file: path=/usr/bin/enum4linux
        src=/opt/enum4linux/enum4linux.pl
        state=link

    - name: Setup Links
      file: path=/usr/bin/nmap-parse
        src=/opt/nmap-parse-output/nmap-parse-output
        state=link

    - name: Copy SysInternals
      copy: src=binaries/SysinternalsSuite.zip dest=/opt/SysinternalsSuite.zip owner=root

    - name: create SysInternals Dir
      file:
        path: /opt/sysinternals
        state: directory

    - name: Extract SysInternals
      unarchive:
        src: /opt/SysinternalsSuite.zip
        dest: /opt/sysinternals

    - name: Delete Zip
      file:
        path: /opt/SysinternalsSuite.zip
        state: absent

    - name: create Loot dir
      file:
        path: /loot
        state: directory

    - name: create postexploitation dir
      file:
        path: /postexploitation
        state: directory

    - name: Setup PostExploitation Links
      file: path=/postexploitation/sysinternals
        src=/opt/sysinternals
        state=link

    - name: Setup PostExploitation Links
      file: path=/postexploitation/lazagne.exe
        src=/opt/lazagne.exe
        state=link

    - name: Setup PostExploitation Links
      file: path=/postexploitation/powersharppack
        src=/opt/powersharppack
        state=link

    - name: Setup PostExploitation Links
      file: path=/postexploitation/sharpcollection
        src=/opt/sharpcollection
        state=link

    - name: Setup PostExploitation Links
      file: path=/postexploitation/powersploit
        src=/opt/powersploit
        state=link

    - name: Setup PostExploitation Links
      file: path=/postexploitation/sharpsploit
        src=/opt/sharpsploit
        state=link

    - name: Setup PostExploitation Links
      file: path=/postexploitation/bloodhound
        src=/opt/bloodhound
        state=link
